# configuration for master/CI branch
-
  branches:
    only:
      - master

  os: Visual Studio 2015
  configuration: Debug
  build:
    project: Lyra.Core.sln
    verbosity: minimal

  version: 0.9.0-ci{build}