# configuration for master/CI branch
-
  branches:
    only:
      - master

  os: Visual Studio 2017
  configuration: Debug
  before_build:
  - ps: .\appveyor.ps1
  build:
    project: Lyra.Core.sln
    verbosity: minimal

  version: 0.9.0-ci{build}
