# configuration for master/CI branch
-
  branches:
    only:
      - master

  os: Visual Studio 2015
  configuration: AppVeyor
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '0.9.0.{build}'
    assembly_file_version: '0.9.0.{build}'
    assembly_informational_version: '0.9.0.{build}'
  build:
    project: Lyra.Core.sln
    verbosity: minimal

  version: 0.9.0-ci{build}